# Default values for sample-app-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: "sample-app"
fullnameOverride: "sample-app-2tier"
namespace: "default"

frontend:
  name: sample-app-frontend
  app:
    name: frontend
    replicaCount: 2
  service:
    name: sample-app-frontend
    type: ClusterIP
    port: 80
  image:
    repository: acrpocpb.azurecr.io/frontend
    tag: latest
    pullPolicy: Always

webapi:
  name: sample-app-webapi
  app:
    name: webapi
    replicaCount: 2
  service:
    name: sample-app-webapi
    type: ClusterIP
    port: 80
  image:
    repository: acrpocpb.azurecr.io/webapi
    tag: latest
    pullPolicy: Always
      
nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
