apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webapi.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.webapi.app.name }}
    helm.sh/chart: {{ include "sample-app-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.webapi.service.type }}
  ports:
    - port: {{ .Values.webapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.webapi.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
