apiVersion: v1
kind: Service
metadata:
  name: sample-frontend
  labels:
    app: sample-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: sample-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-frontend-deployment
  labels:
    app: sample-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-frontend
  template:
    metadata:
      labels:
        app: sample-frontend
    spec:
      containers:
      - name: frontend
        image: acrpocpb.azurecr.io/frontend:latest
        env:
        - name: WebAPI
          value: http://sample-webapi
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azurefile        
---
apiVersion: v1
kind: Service
metadata:
  name: sample-webapi
  labels:
    app: sample-webapi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: sample-webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapi-deployment
  labels:
    app: sample-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-webapi
  template:
    metadata:
      labels:
        app: sample-webapi
    spec:
      containers:
      - name: webapi
        image: acrpocpb.azurecr.io/webapi:latest
        ports:
        - containerPort: 80